# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "V4TkRK4GXFHxnhCVl/bJf7piwBY+JjoqqNVGKHUoPzNESyZcAYs6kH4s5i71cLWfbUiWdKrvPWYC/b5TzOENcNfSywgFs7Io1Qa/oS9iC5O27WOod5kNJc5sSTB2P61JWOczN8X6qdj6LPV9guHDtskgyI18kCdjnH5KOS1bUOnPwHlpajkJVfay+NQaWLY6GCp01IcXbgyvz+QAr0/NTB5mQT46AIwv3VOI9qf5Z395+8EqoffP68udM992ccOBWkM33d+GKSJauh6cIO7F/lJaRfcizBXN8NaHS1LBQQGSau4vb8/Ku+Nbr0xRn8ikw8q3Pw4IVkX0MsApIXWFjb7BdjjlcZJiJkhvbnaVRvjZQ5+iEgqH6ELX6heVi+g2Vcr591kZwoHKuc8sOwYdaEHgiM086o7fmJr7jqRDDPL5DsWUAjIa71vsswKLfpBty6tpAPpbJ+OsuUhTt6crd2u/2NXv4dTpemqoyGGbJ6AaLlYNTlJbYmJ6T3qibKmK/5sXMiu1K1nEG4w+xcND6pza5RmL5OSs3XrP+jvO6Erqenfo+KfT33LgRyvjnN0n12jVIL/FJI+QoRQjQ/ibVB1lIzTc4nI1NAm7b4sQF8hAMivKD0rEjv1IWuRkYSqxNphZgPEplR5F4+w2wVHxnOkXF7YrE02gMt+YCKjKWlE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
