travis:
  secure:
    BINSTAR_TOKEN: k9l7MMGbURwo/kzPU4Jllm9Vx4XsAyskklmr8tGEOhmU65o/QjEI8AUuMdDBowOpan1LoOLiyKpmXfnl8NHhecacqhxbEIF2RH4M2Re/m+ywz1c1oTQJwprMBVLi5b2Ass1pNxYswtrDTXtxuq8auJL4a8cA7I2kARqQ0P97XQl+BBpfnn9D/vqSzUdbNS2u6YV5clmU/Nl++yO5mrKZ9Dh8jnhxmUPTZW7w8hbVhgRWLENbNOVmy3ECF0gsi0/wUJIM6eqInvxYgsuHLNOB0+O0jlsbkQDpdAd5z3XnLcz1Y9++41xJzPLK80GJ4AYkRnejbb4g9RAwMEEnwy7pmcJWJ3h29jHfnWysBTOmgsSZgriVm02ugyWFMYLBR0RWUf3ceu8zvYtlH/MO/1i2Ie4jG+tp3ocCq34JhOGEJUdTPvQY4+bbMMNN13QoXmjtglGr65GAMF41LI2LKgpRCqcNzAjUcuJu/Hdx1KUVmR9eDylVdUBzoxKIhP6m/lCeTR3XVSSRIR7KyUelWs2o9OtSNK4VYZYRVwg38EvrlCUPZRuKNQcVOlVfRQuzhQCfwh5UK46kjFIBtYO5vUuDdl1SZDudFjVPrqGOy8eewAUZa2hwo7mrB3HJKYv/t8oBWCtVP/fjXAJcVK72TlHZ0dK5B+XrQ6G0CjNH/UFA2ls=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
