travis:
  secure:
    BINSTAR_TOKEN: V4TkRK4GXFHxnhCVl/bJf7piwBY+JjoqqNVGKHUoPzNESyZcAYs6kH4s5i71cLWfbUiWdKrvPWYC/b5TzOENcNfSywgFs7Io1Qa/oS9iC5O27WOod5kNJc5sSTB2P61JWOczN8X6qdj6LPV9guHDtskgyI18kCdjnH5KOS1bUOnPwHlpajkJVfay+NQaWLY6GCp01IcXbgyvz+QAr0/NTB5mQT46AIwv3VOI9qf5Z395+8EqoffP68udM992ccOBWkM33d+GKSJauh6cIO7F/lJaRfcizBXN8NaHS1LBQQGSau4vb8/Ku+Nbr0xRn8ikw8q3Pw4IVkX0MsApIXWFjb7BdjjlcZJiJkhvbnaVRvjZQ5+iEgqH6ELX6heVi+g2Vcr591kZwoHKuc8sOwYdaEHgiM086o7fmJr7jqRDDPL5DsWUAjIa71vsswKLfpBty6tpAPpbJ+OsuUhTt6crd2u/2NXv4dTpemqoyGGbJ6AaLlYNTlJbYmJ6T3qibKmK/5sXMiu1K1nEG4w+xcND6pza5RmL5OSs3XrP+jvO6Erqenfo+KfT33LgRyvjnN0n12jVIL/FJI+QoRQjQ/ibVB1lIzTc4nI1NAm7b4sQF8hAMivKD0rEjv1IWuRkYSqxNphZgPEplR5F4+w2wVHxnOkXF7YrE02gMt+YCKjKWlE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
