travis:
  secure:
    BINSTAR_TOKEN: koN/2IrN4ea9aUqIMuuWyIWTpssfO4AMFSXUSsG9nyaA4EatICFvdORedn3rgbZkhPT0xbD+hpvb29PqBfe0GKPvRQdzRmg08IgAAyzx3YIn3kkQzoWCtM/Er0C9YSXNaJn11UYPX3MZp11nKZmtr9PgBqcfUVyccNIAfSim/2G/bE9oIBOljkx1ckr/e33JupN7GBrgkOcH0RUVRBIwF/eKGxF9tY3QVFdXomEevetso8nzU5BDxPL7QZh8AVERRoGqW4h1T4SQbxsgnuOJOYaZ7xcwpmptpnrOBTmMvfuz3RnvzySZvctN2bBJCDn0Gj7gWuyt9GHV//cRCGbWxiilr0keHq98jOHhOsvpKBvTVzuSqILhTN+W1vYWQyUBT/3mNZySkgRuKMIHB7eMbqVlUe7nl5BtRnbZySfKCEiUKJPJxuDpA2FjbITScjdVLlwda1R+vqT3gZ1emvGAhbeZDxmF2eiPY9l4gfKu8jHDehgMcAtrkVR1Zlsa4CSBb6uLLlx7n0ZS4v6BPLFfYEA2FE1D2l6GTYpcg3f1KjyLmHyE2Ao52IQWjm/ybhEXlYnzwcdGglh9ZId4Banj/r0Tz6oBaz+0TCQIjga1FlNayhiWUSXAxQs6ue8iw9a/xE5iZg71VRzThQvkC0Algk0GIccPFbVLoVbdtT7WZko=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
