travis:
  secure:
    BINSTAR_TOKEN: eiZ8RKquSjeCfBMOay30Z0+umBH7Ah1r5fS7lfkek9jTCuRKKNADqvpag7e/BwWuQJyTOP0Zx6ntjsTWaiEi8nJM3ewCMkm/FgXpSo+s3vQAtG2eY+k5qG+Ij2Ba4dn1/oIZXExA3c8Zlar+fLCbdeNgGqhOjKm4ga1fw1HzxRtpJbavsFDnAO3s/JkDtPr6b7HT8Rx9kMbobXSbwbbgRzpoHRAt1fPHpjpe8sbqYvHuk4CcF+otff6ImKEF4zeMJ0RkmffbZgTOh41v1cqVBiQb84xrEOf1vYjlY0a/f0KBA4m4ikHIGOFZpVpozytC9SquKh55a94VlmCWKgNQwW2il99BZ11TUhstuysHU+bhyotgk7fj7KnhzQzYklWD93+aVNnVieeJhBdfYuKEc7BQDy39FkEm5B2KOEZUouKmgOz/N0LYTY24BQqvsHrk/9Rttnu/vMJDar8rrAU9d+l7IZ6iLjsJQtDeISDMZ/YjQlp3LC7MsAhWxW1hrXaAGB6Un0m1Tv/94vV6uaGLNTtbGKuBqt1LecdN0GyZSoS1lFqCF9+LKNbJEsMI8QVLYr+ZgMvTOJDIQ2ZqwPwOlK6WEhm+XpWqmjmC9rd9FBglW/IEJP2TS+LfmuX2FRECEqNnzF2twpBgucUWjJNFHEmGB7QzWCGW1+URl0H4enE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
